//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Z119.Model.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Borrowers = new HashSet<Borrower>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Language { get; set; }
        public string ReleaseYear { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string Note { get; set; }
        public string Price { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SpecialCategoryId { get; set; }
        public Nullable<int> BookShelfId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual BookShelf BookShelf { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        public virtual SpecialCategory SpecialCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrower> Borrowers { get; set; }
    }
}
